name: Backend CI/CD

on:
  push:
    branches:
      - master
      - staging

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run lint
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /pcs-be/
          remote_host: ec2-54-251-180-24.ap-southeast-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACBZPk/XkEAFU21I2MN3FdtayDNDU2ugcwFPjlJptAoX+QAA
AIiu3lExrt5RMQAAAAtzc2gtZWQyNTUxOQAAACBZPk/XkEAFU21I2MN3FdtayDND
U2ugcwFPjlJptAoX+QAAAEAwUQIBATAFBgMrZXAEIgQgJ9EXqrQaBdtG3s0q9Ox8
31k+T9eQQAVTbUjYw3cV21rIM0NTa6BzAU+OUmm0Chf5AAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----"